packages:
  - packages/*
  - apps/*

catalog:
  '@babel/core': ^7.24.0
  '@jupyterlab/application': ^4.4.4
  '@jupyterlab/apputils': ^4.5.4
  '@jupyterlab/builder': ^4.0.0
  '@jupyterlab/docregistry': ^4.4.4
  '@jupyterlab/fileeditor': ^4.0.0
  '@jupyterlab/services': ^7.0.0
  '@lumino/widgets': ^2.0.0
  '@niivue/dicom-loader': ^1.0.0
  '@niivue/niivue': ^0.61.0
  '@playwright/test': ^1.47.2
  '@preact/preset-vite': ^2.9.1
  '@preact/signals': ^2.0.1
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/preact': ^3.2.3
  '@types/node': ^22.16.4
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/vscode': ^1.70.0
  '@typescript-eslint/eslint-plugin': ^8.12.2
  '@typescript-eslint/parser': ^8.12.2
  '@vitejs/plugin-legacy': ^5.4.3
  '@vitest/coverage-v8': ^2.1.3
  autoprefixer: ^10.4.18
  concurrently: 9.2.0
  copy-webpack-plugin: ^13.0.0
  css-loader: ^6.7.1
  esbuild: ^0.20.2
  eslint: ^9.13.0
  eslint-config-prettier: ^9.0.0
  eslint-plugin-prettier: ^5.0.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  husky: ^9.1.7
  less: ^4.1.3
  lint-staged: ^16.1.2
  mkdirp: ^1.0.3
  npm-run-all: ^4.1.5
  postcss: ^8.4.47
  preact: ^10.24.1
  prettier: ^3.0.0
  react-router-dom: ^6.26.0
  rimraf: ^5.0.1
  source-map-loader: ^1.0.2
  style-loader: ^3.3.2
  stylelint: ^15.10.1
  stylelint-config-recommended: ^13.0.0
  stylelint-config-standard: ^34.0.0
  stylelint-csstree-validator: ^3.0.0
  stylelint-prettier: ^4.0.0
  tailwindcss: ^3.4.13
  turbo: ^2.0.0
  typescript: ^5.6.3
  typescript-eslint: ^8.0.0
  vite: ^5.4.10
  vite-plugin-dts: ^4.5.4
  vite-plugin-pwa: ^0.21.1
  workbox-build: ^7.0.0
  yjs: ^13.5.40
