import { resolve } from 'path'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: {
    alias: {
      // `dcm2niix-worker` is a virtual module generated by vite.config.ts, which
      // vitest does not load. Alias it to a stub so tests can import components
      // that pull in the dicom loader (e.g. NiiVueCanvas).
      'dcm2niix-worker': resolve(__dirname, 'src/test/stubs/dcm2niix-worker.ts'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test-setup.ts'],
    css: true,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules/**', 'build/**', 'dist/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json', 'json-summary'],
      reportsDirectory: './coverage/unit',
      include: ['src/**/*.{ts,tsx}'],
      exclude: ['src/**/*.d.ts', 'src/main.tsx', 'src/test-setup.ts', 'src/test/**'],
    },
  },
})
