// Single source of truth -> every app icon. Reads the one committed master
// (branding/niivue-icon.png) and derives all per-app icons so we never
// hand-maintain N copies of the brand.
//
//   pnpm generate:icons          # regenerate everything (run after the master
//                                # changes, then commit niivue-logo.ts)
//   node scripts/generate-icons.mjs <vscode|pwa|jupyter|logo|all>
//
// Each app's build regenerates only its own icon(s) (a disjoint target), so
// `turbo build` can run them in parallel without two processes racing on the
// same file. The desktop bundle's multi-format .icns/.ico are produced by the
// Tauri CLI instead (see `pnpm generate:icons:tauri`).
//
// The master is the upstream niivue brand mark (a neon brain on a near-black
// field, 1024x1024, no alpha). Two derivations are made from it:
//   - transparent: the dark field is keyed out via luminance -> alpha, so the
//     mark sits flush on any surface (Explorer/Jupyter file icons, viewer logo).
//   - opaque: the master as-is over its own dark field (the marketplace listing
//     and the PWA, where a solid tile reads better against light chrome).
// Outputs are palette-quantized PNGs (~5x smaller than RGBA) for distribution.

import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const MASTER = resolve(root, 'branding/niivue-icon.png')
const out = (p) => resolve(root, p)

// Shared small-PNG options. Palette/quantized output mirrors
// apps/pwa/pwa-assets.config.ts and keeps every shipped icon tiny.
const png = (colors = 256) => ({ compressionLevel: 9, palette: true, colors, effort: 10 })

// Transparent RGBA buffer: alpha = brightness of the brightest channel, with the
// near-black field floored to fully transparent. Keeping the glow's mid-range
// alpha preserves the neon falloff instead of hard-cutting it. max(r,g,b) (not
// luminance) so saturated cyan/magenta strokes stay fully opaque.
async function transparentRaw() {
  const { data, info } = await sharp(MASTER)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const FLOOR = 18 // at/below this (the ~#0a0a10 field) -> invisible
  for (let i = 0; i < data.length; i += 4) {
    const m = Math.max(data[i], data[i + 1], data[i + 2])
    data[i + 3] = m <= FLOOR ? 0 : Math.min(255, Math.round(((m - FLOOR) * 255) / (255 - FLOOR)))
  }
  return { data, width: info.width, height: info.height }
}

// Each target writes a disjoint set of files. `logo` is the only one that is
// committed (it is imported from @niivue/react source); the rest are gitignored
// and regenerated by their app's build.
const targets = {
  async vscode(ctx) {
    await ctx.transparent(128).toFile(out('apps/vscode/language-icon.png')) // Explorer/tab icon
    await ctx.opaque(128).toFile(out('apps/vscode/icon.png')) // marketplace listing
  },
  async jupyter(ctx) {
    await ctx.transparent(128).toFile(out('apps/jupyter/style/niivue-icon.png'))
  },
  async pwa(ctx) {
    await mkdir(out('apps/pwa/public'), { recursive: true })
    // Served logo + @vite-pwa/assets-generator source. 512 keeps PWA behavior.
    await ctx.opaque(512).toFile(out('apps/pwa/public/logo.png'))
  },
  async logo(ctx) {
    // In-app viewer mark as a base64 data-URI TS module (transparent, 128
    // colors, a few KB). A string, not a *.png import, because @niivue/react is
    // type-checked from source by consumers without an ambient *.png module.
    // This is the one generated icon that is committed (it is imported from
    // source). We stamp the master's hash into it so CI can verify it has not
    // gone stale - a content check, not a byte-compare of the palette PNG, which
    // is not guaranteed reproducible across platforms.
    const buf = await ctx.transparent(96, 128).toBuffer()
    const masterSha = createHash('sha256').update(await readFile(MASTER)).digest('hex')
    await writeFile(out('packages/niivue-react/src/assets/niivue-logo.ts'), logoModule(buf, masterSha))
  },
}

async function main() {
  const which = process.argv[2] || 'all'
  const names = which === 'all' ? Object.keys(targets) : [which]

  const t = await transparentRaw()
  const ctx = {
    transparent: (size, colors) =>
      sharp(t.data, { raw: { width: t.width, height: t.height, channels: 4 } })
        .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png(png(colors)),
    opaque: (size) => sharp(MASTER).resize(size, size).png(png()),
  }

  for (const name of names) {
    if (!targets[name]) throw new Error(`unknown icon target "${name}" (expected: ${Object.keys(targets).join(', ')}, all)`)
    await targets[name](ctx)
  }
  console.log(`Generated icons [${names.join(', ')}] from branding/niivue-icon.png`)
}

function logoModule(buf, masterSha) {
  return `// GENERATED by scripts/generate-icons.mjs from branding/niivue-icon.png.
// Do not edit by hand; run \`pnpm generate:icons\` to refresh.
// icon-master-sha256: ${masterSha}
//
// The niivue brand mark shown in the top bar (see Menu.tsx). Inlined as a
// base64 data URI rather than a *.png import: @niivue/react is type-checked
// *from source* by the PWA and Streamlit frontends, which do not all declare an
// ambient *.png module. A plain string sidesteps that while still inlining.
export const niivueLogo =
  'data:image/png;base64,${buf.toString('base64')}'
`
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
