name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: python -m pip install -U "jupyterlab>=4.0.0,<5"

      - name: Lint the extension
        run: |
          set -eux
          npm run eslint:check
          npm run prettier:check
        working-directory: niivue-jupyter

      - name: Test the extension
        run: |
          set -eux
          python -m pip install .[test]
          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-niivue.*OK"
          python -m jupyterlab.browser_check
        working-directory: niivue-jupyter

      - name: Package the extension
        run: |
          set -eux
          pip install build
          python -m build
          pip uninstall -y "jupyterlab_niivue" jupyterlab
        working-directory: niivue-jupyter

      - name: Upload extension packages
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: niivue-jupyter/dist/jupyterlab_niivue*
          if-no-files-found: error

  test_isolated:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
      - name: Install and Test
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)
          
          pip install "jupyterlab>=4.0.0,<5" jupyterlab_niivue*.whl
          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-niivue.*OK"
          python -m jupyterlab.browser_check --no-browser-test

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
        with:
          ignore_glob: "niivue-jupyter/static/**"
